describe('Pruebas exploración de blogs ghost',  { 
  viewportHeight: 689.17,
  viewportWidth: 1030,},() => {
it('login', () => {
  cy.visit('https://ghost-u4ew.onrender.com/ghost/#/setup/one')
  cy.wait(1000)
  cy.screenshot('Ingresar pagina ghost')
  cy.get('input[name="identification"]').type('h.sosa@uniandes.edu.co')
  cy.get('input[name="password"]').type('Colombia1*')
  cy.screenshot('Ingresar Datos Login')
  cy.get('button[class="login gh-btn gh-btn-blue gh-btn-block gh-btn-icon ember-view"]').click()
  cy.screenshot('Login')
  cy.url().should('include', '/site')
  cy.get('a[title="New post"]').click()
  cy.screenshot('Crear Post')
  cy.wait(1000)
  cy.get('textarea[class="gh-editor-title ember-text-area gh-input ember-view"]').type('Post Pruebas Automatizadas')
  cy.get('div[class="koenig-editor__editor __mobiledoc-editor __has-no-content"]').type('Esta es un prueba automatizada para la universidad de los andes')  
  cy.screenshot('Datos del post')
  cy.wait(2000)
  cy.contains('div[class="ember-view ember-basic-dropdown-trigger ember-basic-dropdown-trigger--right ember-basic-dropdown-trigger--below  gh-btn gh-btn-outline gh-publishmenu-trigger"]').click()  
  cy.contains('button[class="gh-btn gh-btn-blue gh-publishmenu-button gh-btn-icon ember-view"]').click()
  cy.screenshot('Publicar post')
  cy.get('button[class="gh-btn gh-btn-black gh-btn-large"]').click()
  cy.get('button[data-test-button="confirm-publish"]').click()
  cy.screenshot('Confirmar publicacion')
  cy.get('div[class="gh-post-bookmark-title"]').contains('Post Pruebas Automatizadas')
  cy.screenshot('Validación creación post')
  })
})
